
services:
  app1:
    build: ./app
    container_name: app1
    hostname: app1
    ports:
      - "8001:8000"

  app2:
    build: ./app
    container_name: app2
    hostname: app2
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.iphash.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
