version: "3.9"

services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - "8001:8000"

  app2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
